theme: blowfish
baseURL: 'https://x53.studio/'
title: X53 Studio
googleAnalytics: G-00DJ4XW7K6
defaultContentLanguage: en
pluralizeListTitles: 'true'
enableRobotsTXT: true
summaryLength: 100
buildDrafts: false
buildFuture: false
enableEmoji: true
pagination:
  pagerSize: 100
imaging:
  anchor: Center
taxonomies:
  tag: tags
  category: categories
  author: authors
  series: series
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
outputs:
  home:
    - HTML
    - RSS
    - JSON
related:
  threshold: 0
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 100
    - name: series
      weight: 50
    - name: authors
      weight: 20
    - name: date
      weight: 10
    - applyFilter: false
      name: fragmentrefs
      type: fragments
      weight: 10
