main:
  - name: Posts
    pageRef: posts
    weight: 10
#  - name: Projects
#    pageRef: projects
#    weight: 20
  - name: Resources
    pageRef: resources
    weight: 30
  - name: Tags
    pageRef: tags
    weight: 40
  - pre: github
    url: 'https://github.com/pedro0x53'
    weight: 50
